package com.aifoundry.platform.common.error;

public enum ErrorCode {
  VALIDATION_ERROR,
  INVALID_PROMPT,
  PROVIDER_UNAVAILABLE,
  PROVIDER_TIMEOUT,
  MODEL_NOT_FOUND,
  RAG_DOCUMENT_NOT_FOUND,
  RAG_INGESTION_FAILED,
  RAG_RETRIEVAL_FAILED,
  AGENT_NOT_FOUND,
  AGENT_EXECUTION_FAILED,
  APPROVAL_REQUIRED,
  UNAUTHORIZED,
  FORBIDDEN,
  INTERNAL_ERROR
}
